version: "1.0"
info:
  model: int-scaffold
packages:
- name: MirsExxonDADAProject
  gitServerName: MirsGit
  gitUrl: https://github.com/mirhussainali/MirsExxonDADAProject
  gitUsername: mirhussainali
  gitBranch: main
- name: ExxonDemo
  version: "1.0"
  gitServerName: MirsGit
  gitUrl: https://github.com/mirhussainali
  gitUsername: mirhussainali
  gitBranch: main
services:
- serviceName: project.mirsexxondada.integrations:DADA_ExxonFlow1
  packages:
  - name: MirsExxonDADAProject
    version: "1.0"
  - name: ExxonDemo
    version: "1.0"
- serviceName: exxonmobil.flowservices:welcomeService
  packages:
  - name: ExxonDemo
    version: "1.0"
- serviceName: exxonmobil.utils.string:multiConcat
  packages:
  - name: ExxonDemo
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.927
- serviceName: exxonmobil.utils.date:getDayOfWeek
  packages:
  - name: ExxonDemo
    version: "1.0"
- serviceName: project.mirsexxondada.integrations:DADA_ExxonFlow2
  packages:
  - name: MirsExxonDADAProject
    version: "1.0"
  - name: ExxonDemo
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.927
