version: "1.0"
info:
  model: int-scaffold
packages:
- name: MirsExxonDADAProject
  gitServerName: MirsGit
  gitUrl: https://github.com/mirhussainali/MirsExxonDADAProject
  gitUsername: mirhussainali
  gitBranch: main
- name: ExxonDemo
  gitServerName: MirsGit
  gitUrl: https://github.com/mirhussainali
  gitUsername: mirhussainali
  gitBranch: main
